[package]
name = "rsst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
quick-xml = "0.22.0"
rusqlite = { version = "0.27.0", features = ["bundled", "array"] }
